services:
  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    volumes:
      - pilot_postgresql:/var/lib/pilot_postgres/data
    environment:
      - POSTGRES_USER=pilot
      - POSTGRES_PASSWORD=pilot
      - PGDATA=/var/lib/pilot_postgres/data
      - LANG=en_GB.utf8
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
  contractor:
    build: ./contractor_app
    volumes:
      - ./contractor_app:/app
    ports:
      - "3010:3000"
    depends_on:
      - db
      - rabbitmq
  manager:
    build: ./manager_app
    volumes:
      - ./manager_app:/app
    ports:
      - "3011:3000"
    depends_on:
      - db
      - rabbitmq

volumes:
  pilot_postgresql:
  rabbitmq_data:
  rabbitmq_log: